# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccsm < Formula
  desc "Claude Code Session Manager — list, search, and browse saved Claude Code sessions"
  homepage "https://github.com/nemethk/claude-code-session-manager"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nemethk/claude-code-session-manager/releases/download/v0.1.1/ccsm_darwin_amd64.tar.gz"
      sha256 "b52332c44e18904d93479d32bf923184fe37531485cddbdc8a6b6c12d8f94ace"

      define_method(:install) do
        bin.install "ccsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nemethk/claude-code-session-manager/releases/download/v0.1.1/ccsm_darwin_arm64.tar.gz"
      sha256 "0bdf8e01dc4c386668608f27c7a7331110f8308ce8b7d29782bb09ff2fd59570"

      define_method(:install) do
        bin.install "ccsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nemethk/claude-code-session-manager/releases/download/v0.1.1/ccsm_linux_amd64.tar.gz"
      sha256 "bf17ac2edc2d30c87f82a968625bfc0465de412a777bea3e131f5855cfb0b653"
      define_method(:install) do
        bin.install "ccsm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nemethk/claude-code-session-manager/releases/download/v0.1.1/ccsm_linux_arm64.tar.gz"
      sha256 "744537bf83a79c437b3ec100582cdbf4e00c91837644165c957f6c49ef93eb9d"
      define_method(:install) do
        bin.install "ccsm"
      end
    end
  end
end
