# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudeenv < Formula
  desc "Claude Code environment manager — activate domain-specific skills, agents, and rules per project"
  homepage "https://github.com/nemethk/claudeenv"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nemethk/claudeenv/releases/download/v0.1.0/claudeenv_darwin_amd64.tar.gz"
      sha256 "337d148d3e5faea3a362d5ed4dd9a8bf194bfa38081eb772f659891a57e983e8"

      define_method(:install) do
        bin.install "claudeenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nemethk/claudeenv/releases/download/v0.1.0/claudeenv_darwin_arm64.tar.gz"
      sha256 "287c782259eb2f476a048016578acb688ad5d49d761280947e27bef0dd04b943"

      define_method(:install) do
        bin.install "claudeenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nemethk/claudeenv/releases/download/v0.1.0/claudeenv_linux_amd64.tar.gz"
      sha256 "1cdf40fa663b755d8fc66c6d02775022f1e94701572ea8b4e4b288cb02a44df8"
      define_method(:install) do
        bin.install "claudeenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nemethk/claudeenv/releases/download/v0.1.0/claudeenv_linux_arm64.tar.gz"
      sha256 "5499896f8484069a6cacfa6b126e47184cdcdb35a9a5a41d465dbe0ce476105a"
      define_method(:install) do
        bin.install "claudeenv"
      end
    end
  end
end
